ignoredBuiltDependencies:
  - '@tensorflow/tfjs-node-gpu'
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@tensorflow/tfjs-node'
  - canvas
  - core-js
  - mmmagic
  - onnxruntime-node
  - protobufjs
  - sharp
